name: Update repository card

on:
  workflow_dispatch:
  schedule:
    - cron: '17 0 * * *'

permissions:
  contents: write
  issues: read
  pull-requests: read

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: Haruko386/Recent-working-on@main
        with:
          repository: Haruko386/Gogit
