name: Generate 3D City

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Generate City Skyline
        uses: Haruko386-UnOffical/github-city@main
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          theme: cityNight 

      - name: Create output directory
        run: |
          mkdir -p img
          mv city.svg img/city.svg

      - name: Push city to output branch
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: output
          build_dir: img
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
